theme = "catppuccin_mocha"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[keys.insert]
C-s = ":w"
C-c = "normal_mode"
C-space = "completion"
C-z = "undo"
"C-/" = "toggle_comments"
C-w = "no_op"

[keys.normal]
"C-/" = ["toggle_comments", ":w"]
C-c = "no_op"
C-q = ":quit!"

