# Languages TOML

[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }

[[language]]
name = "json"
formatter = { command = 'npx', args = [ "prettier", "--parser", "json"] }

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "rust"
auto-format = true

[[language]]
name = "python"
language-servers = ["pylsp"]
roots = [".git"]

[[language]]
name = "markdown"
formatter = { command = "npx", args = [ "prettier", "--parser", "markdown", "--prose-wrap", "always" ] }
auto-format = true
